-- ============================================================
-- 025 KEYDROP クーポン機能 Phase A（DB）
-- 管理画面でクーポン発行 → ユーザーがコード入力 → 割引適用
-- 設計の肝：割引は必ずサーバ（SECURITY DEFINER関数 / Edge）で確定。
--   - keydrop_check_coupon  … 読み取り検証（プレビュー用・anon可）
--   - keydrop_redeem_coupon … 確定（原子的・service_roleのみ・二重使用/競合防止）
-- 共有テーブル（札幌/那覇 共通）。store列で 'all'|'spk'|'nha' を出し分け。
-- Supabase ckrxttbnawkclshczsia の SQL Editor で RUN。
-- ============================================================

-- ---------- テーブル：クーポン本体 ----------
create table if not exists public.keydrop_coupons (
  id              bigint generated by default as identity primary key,
  code            text not null,                          -- 入力コード（大文字で運用）
  discount_type   text not null default 'percent'         -- 'percent' | 'fixed'
                    check (discount_type in ('percent','fixed')),
  discount_value  numeric not null default 0,             -- percent=%(0-100) / fixed=円
  max_discount_yen integer,                               -- ％時の割引上限（任意・nullで無制限）
  min_amount_yen  integer not null default 0,             -- 最低利用額（これ未満は不可）
  applies_to      text not null default 'total'           -- 'total'(基本+OP) | 'base'（将来用）
                    check (applies_to in ('total','base')),
  store           text not null default 'all'             -- 'all' | 'spk' | 'nha'
                    check (store in ('all','spk','nha')),
  valid_from      timestamptz,                            -- 開始（null=制限なし）
  valid_until     timestamptz,                            -- 終了（null=制限なし）
  max_uses        integer,                                -- 総使用上限（null=無制限）
  used_count      integer not null default 0,             -- 使用済み回数
  per_email_once  boolean not null default false,         -- 1メール1回まで
  active          boolean not null default true,          -- 有効/停止
  memo            text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
-- コードは大文字で一意（小文字入力でも衝突させない）
create unique index if not exists keydrop_coupons_code_uidx on public.keydrop_coupons (upper(code));
create index if not exists keydrop_coupons_active_idx on public.keydrop_coupons (active, store);

-- updated_at 自動更新
create or replace function public.keydrop_coupons_touch() returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;
drop trigger if exists trg_keydrop_coupons_touch on public.keydrop_coupons;
create trigger trg_keydrop_coupons_touch before update on public.keydrop_coupons
  for each row execute function public.keydrop_coupons_touch();

-- ---------- テーブル：利用履歴 ----------
create table if not exists public.keydrop_coupon_redemptions (
  id              bigint generated by default as identity primary key,
  coupon_id       bigint references public.keydrop_coupons(id) on delete set null,
  code            text not null,
  reservation_id  text,                                   -- KD-… / KDN-…
  email           text,
  base_amount     integer,                                -- 割引前
  discount_amount integer,                                -- 割引額
  final_amount    integer,                                -- 割引後
  store           text,
  redeemed_at     timestamptz not null default now()
);
create index if not exists keydrop_redemp_coupon_idx on public.keydrop_coupon_redemptions (coupon_id);
create unique index if not exists keydrop_redemp_resv_uidx on public.keydrop_coupon_redemptions (reservation_id)
  where reservation_id is not null;   -- 1予約1回（冪等性・再試行で二重加算しない）

-- ---------- 予約テーブルに coupon_code 列 ----------
alter table public.reservations     add column if not exists coupon_code text;
alter table public.nha_reservations add column if not exists coupon_code text;

-- ============================================================
-- 関数①：読み取り検証（プレビュー用・割引額/最終額/NG理由を返す）
--   anon から呼べる（SECURITY DEFINER）。入力したコードのみ検証＝一覧は漏れない。
-- 戻り：{ok, code, discount_type, discount_value, discount, final, reason}
-- ============================================================
create or replace function public.keydrop_check_coupon(
  p_code text, p_store text default 'spk', p_amount integer default 0, p_email text default null
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  c public.keydrop_coupons%rowtype;
  v_disc integer := 0;
  v_used integer;
begin
  if p_code is null or btrim(p_code) = '' then
    return jsonb_build_object('ok', false, 'reason', 'empty');
  end if;
  select * into c from public.keydrop_coupons where upper(code) = upper(btrim(p_code)) limit 1;
  if not found then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  if not c.active then return jsonb_build_object('ok', false, 'reason', 'inactive'); end if;
  if c.store <> 'all' and c.store <> coalesce(p_store,'spk') then
    return jsonb_build_object('ok', false, 'reason', 'store');
  end if;
  if c.valid_from is not null and now() < c.valid_from then
    return jsonb_build_object('ok', false, 'reason', 'not_started');
  end if;
  if c.valid_until is not null and now() > c.valid_until then
    return jsonb_build_object('ok', false, 'reason', 'expired');
  end if;
  if coalesce(p_amount,0) < c.min_amount_yen then
    return jsonb_build_object('ok', false, 'reason', 'min_amount', 'min_amount_yen', c.min_amount_yen);
  end if;
  if c.max_uses is not null and c.used_count >= c.max_uses then
    return jsonb_build_object('ok', false, 'reason', 'exhausted');
  end if;
  if c.per_email_once and p_email is not null and btrim(p_email) <> '' then
    select count(*) into v_used from public.keydrop_coupon_redemptions
      where coupon_id = c.id and lower(email) = lower(btrim(p_email));
    if v_used > 0 then return jsonb_build_object('ok', false, 'reason', 'used'); end if;
  end if;
  -- 割引計算
  if c.discount_type = 'percent' then
    v_disc := floor(coalesce(p_amount,0) * c.discount_value / 100.0);
    if c.max_discount_yen is not null then v_disc := least(v_disc, c.max_discount_yen); end if;
  else
    v_disc := floor(c.discount_value);
  end if;
  v_disc := greatest(0, least(v_disc, coalesce(p_amount,0)));  -- 0〜金額の範囲に丸め
  return jsonb_build_object(
    'ok', true, 'code', upper(c.code),
    'discount_type', c.discount_type, 'discount_value', c.discount_value,
    'discount', v_disc, 'final', coalesce(p_amount,0) - v_disc
  );
end $$;

-- ============================================================
-- 関数②：確定（原子的）— Edge(keydrop-pay)が service_role で呼ぶ
--   行ロック→再検証→履歴INSERT→used_count+1。1予約1回（冪等）。
-- 戻り：{ok, code, discount, final} or {ok:false, reason}
-- ============================================================
create or replace function public.keydrop_redeem_coupon(
  p_code text, p_store text, p_amount integer, p_email text, p_resv text
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  c public.keydrop_coupons%rowtype;
  v_disc integer := 0;
  v_used integer;
  v_exist public.keydrop_coupon_redemptions%rowtype;
begin
  -- 冪等：同じ予約で既に確定済みなら、その内容を返す（再試行で二重加算しない）
  if p_resv is not null then
    select * into v_exist from public.keydrop_coupon_redemptions where reservation_id = p_resv limit 1;
    if found then
      return jsonb_build_object('ok', true, 'code', v_exist.code,
        'discount', v_exist.discount_amount, 'final', v_exist.final_amount, 'idempotent', true);
    end if;
  end if;

  select * into c from public.keydrop_coupons where upper(code) = upper(btrim(p_code)) for update;
  if not found then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  if not c.active then return jsonb_build_object('ok', false, 'reason', 'inactive'); end if;
  if c.store <> 'all' and c.store <> coalesce(p_store,'spk') then
    return jsonb_build_object('ok', false, 'reason', 'store'); end if;
  if c.valid_from is not null and now() < c.valid_from then
    return jsonb_build_object('ok', false, 'reason', 'not_started'); end if;
  if c.valid_until is not null and now() > c.valid_until then
    return jsonb_build_object('ok', false, 'reason', 'expired'); end if;
  if coalesce(p_amount,0) < c.min_amount_yen then
    return jsonb_build_object('ok', false, 'reason', 'min_amount'); end if;
  if c.max_uses is not null and c.used_count >= c.max_uses then
    return jsonb_build_object('ok', false, 'reason', 'exhausted'); end if;
  if c.per_email_once and p_email is not null and btrim(p_email) <> '' then
    select count(*) into v_used from public.keydrop_coupon_redemptions
      where coupon_id = c.id and lower(email) = lower(btrim(p_email));
    if v_used > 0 then return jsonb_build_object('ok', false, 'reason', 'used'); end if;
  end if;

  if c.discount_type = 'percent' then
    v_disc := floor(coalesce(p_amount,0) * c.discount_value / 100.0);
    if c.max_discount_yen is not null then v_disc := least(v_disc, c.max_discount_yen); end if;
  else
    v_disc := floor(c.discount_value);
  end if;
  v_disc := greatest(0, least(v_disc, coalesce(p_amount,0)));

  insert into public.keydrop_coupon_redemptions
    (coupon_id, code, reservation_id, email, base_amount, discount_amount, final_amount, store)
    values (c.id, upper(c.code), p_resv, p_email, coalesce(p_amount,0), v_disc, coalesce(p_amount,0)-v_disc, coalesce(p_store,'spk'));
  update public.keydrop_coupons set used_count = used_count + 1 where id = c.id;

  return jsonb_build_object('ok', true, 'code', upper(c.code),
    'discount', v_disc, 'final', coalesce(p_amount,0) - v_disc);
end $$;

-- ============================================================
-- RLS / 権限
--   coupons：スタッフ(authenticated)のみ全操作。anonは参照不可＝コード一覧流出を防ぐ。
--   redemptions：authenticatedは参照のみ。
--   検証はSECURITY DEFINER関数経由（anonは入力コードのみ確認可）。
--   確定関数は service_role のみ。
-- ============================================================
alter table public.keydrop_coupons enable row level security;
drop policy if exists coupons_auth_all on public.keydrop_coupons;
create policy coupons_auth_all on public.keydrop_coupons for all to authenticated using (true) with check (true);
grant select, insert, update, delete on public.keydrop_coupons to authenticated;

alter table public.keydrop_coupon_redemptions enable row level security;
drop policy if exists redemp_auth_read on public.keydrop_coupon_redemptions;
create policy redemp_auth_read on public.keydrop_coupon_redemptions for select to authenticated using (true);
grant select on public.keydrop_coupon_redemptions to authenticated;

-- check は anon/authenticated に開放（プレビュー）。redeem は service_role のみ。
revoke all on function public.keydrop_check_coupon(text,text,integer,text) from public;
grant execute on function public.keydrop_check_coupon(text,text,integer,text) to anon, authenticated, service_role;
revoke all on function public.keydrop_redeem_coupon(text,text,integer,text,text) from public, anon, authenticated;
grant execute on function public.keydrop_redeem_coupon(text,text,integer,text,text) to service_role;

-- ---------- 動作確認（任意・RUN後に手動で） ----------
-- insert into keydrop_coupons(code,discount_type,discount_value,store,memo)
--   values ('WELCOME10','percent',10,'all','テスト10%');
-- select keydrop_check_coupon('welcome10','spk',14000);     -- {ok:true, discount:1400, final:12600}
-- select keydrop_check_coupon('NOPE','spk',14000);          -- {ok:false, reason:not_found}
-- select keydrop_redeem_coupon('WELCOME10','spk',14000,'t@example.com','KD-TEST-0001-XXX');
-- delete from keydrop_coupon_redemptions where reservation_id='KD-TEST-0001-XXX';
-- update keydrop_coupons set used_count=used_count-1 where upper(code)='WELCOME10';
